services:
  postgres:
      image: postgres:16
      container_name: cybersecurity-db
      environment:
        POSTGRES_DB: cyberDetective
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - cybersecurity-network

backend:
    build: ./backend
    container_name: cybersecurity-backend
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cyberDetective
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - cybersecurity-network
                                    
frontend:
    build: ./frontend
    container_name: cybersecurity-frontend
    ports:
         - "80:80"
    depends_on:
        - backend
    networks:
        - cybersecurity-network
                                                                    
volumes:
    postgres_data:
    

networks:
    cybersecurity-network:
        driver: bridge